### ISSUE TITLE
PIT not opening on MacOS

### ISSUE THREAD

**Issue by kuadrat** [pudeIko/piva#29]
Cannot be reproduced on Linux.
More information is required.

**Comment by jukue** [comment]
Hi, 
when pushing the button 'open in PIT', the warning is: 

Traceback (most recent call last):
  File "PATH_TO_PIVA/piva/_2Dviewer.py", line 962, in open_pit
    mw = pit.MainWindow()
  File "PATH_TO_DATASLICER/data_slicer/pit.py", line 569, in __init__
    self.set_cmap(DEFAULT_CMAP)
  File "PATH_TO_DATASLICER/data_slicer/pit.py", line 901, in set_cmap
    cmap = load_cmap(cmap_name)
  File "PATH_TO_DATASLICER/data_slicer/cmaps.py", line 233, in load_cmap
    return convert_matplotlib_to_pyqtgraph(cmap_name)
  File "PATH_TO_DATASLICER/cmaps.py", line 126, in convert_matplotlib_to_pyqtgraph
    matplotlib_cmap = colormaps.get_cmap(matplotlib_cmap)
AttributeError: 'ColormapRegistry' object has no attribute 'get_cmap'

Thanks.

**Comment by jukue** [comment]
Not sure, if this has something to do with PIT not opening, but already when starting piva with 'db', there is a warning: 

PATH_TO_PIVA/piva/cmaps.py:195: UserWarning: Package colormaps were not found.
  warnings.warn('Package colormaps were not found.')

**Comment by jukue** [comment]
Changing kuadrat/data_slicer as in [https://github.com/kuadrat/data-slicer/pull/17](url) allows to open PIT in piva. However, 

> PATH_TO_PIVA/piva/cmaps.py:195: UserWarning: Package colormaps were not found. warnings.warn('Package colormaps were not found.')

when starting piva with 'db' remains.
